import { RootLayoutMain } from '@/components';
import { Inter } from 'next/font/google';
import { StrictMode } from 'react';
import { i18nConfig } from '@/utils';
import { Providers } from '@/store';

import { Flowbite } from '@/components/flowbite-react';
import theme from '@/styles/flowbite-theme';

import '@/styles/globals.css';
import { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });

export async function generateStaticParams() {
  const lang = i18nConfig.locales.map((locale) => ({ lang: locale }));
  return lang;
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  return (
    <Providers>
      <html lang={params.lang}>
        <body className={`${inter.className} bg-gray-50 dark:bg-gray-900`}>
          <div id="root">
            <StrictMode>
              <Flowbite theme={{ theme }}>
                <RootLayoutMain>{children}</RootLayoutMain>
              </Flowbite>
            </StrictMode>
          </div>
        </body>
      </html>
    </Providers>
  );
}
