import { RootLayoutMain, DarkModeScript } from '@/components';
import { Inter } from 'next/font/google';
import { Lang, i18nConfig } from '@/utils';
import { Providers } from '@/store';

import '@/styles/globals.css';
import { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });

export async function generateStaticParams() {
  const lang = i18nConfig.Langs.map((locale) => ({ lang: locale }));
  return lang;
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { lang: Lang };
}) {
  // const { lang } = params;
  return (
    <html lang={lang}>
      <body className={`${inter.className} bg-gray-50 dark:bg-gray-900`}>
        <DarkModeScript />
        <Providers>
          <RootLayoutMain lang={lang}>{children}</RootLayoutMain>
        </Providers>
      </body>
    </html>
  );
}

export default RootLayout;
