import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Script from 'next/script';
import { NextIntlClientProvider } from 'next-intl';

import { getLocaleMessages, LangChildrenProps, localeOption } from '@/common';
import { DarkModeScript, LayoutPageMain } from '@/components';
import { StoreProviders } from '@/store';

import '@/styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const generateStaticParams = async () => {
  const locales = localeOption.locales.map((locale) => ({ lang: locale }));
  return locales;
};

const LocaleLayout = async ({
  children,
  params: { locale },
}: LangChildrenProps) => {
  const localeMessages = await getLocaleMessages(locale);

  return (
    <html lang={locale} suppressHydrationWarning>
      <Script src="/__ENV.js" />
      <body className={`${inter.className} bg-gray-50 dark:bg-gray-900`}>
        <DarkModeScript />
        <StoreProviders>
          <NextIntlClientProvider locale={locale} messages={localeMessages}>
            <LayoutPageMain locale={locale}>{children}</LayoutPageMain>
          </NextIntlClientProvider>
        </StoreProviders>
      </body>
    </html>
  );
};

export { generateStaticParams, metadata };
export default LocaleLayout;
